### ISSUE TITLE
Ros2 Humble - parameter reconfigure for hoverboard_driver_node not working

### ISSUE THREAD

**Issue by tomy983** [alex-makarov/hoverboard-driver#32]
Ros2 Humble, hoverboard driver for all the rest is working fine (thank you!!)

I wanted to try to configure the PID controller, so I enabled it as written in the readme. Obviously the motors started spinning like crazy :-) 
I wanted to reconfigure it, but could not. I also could not figure out where and how to set (and pass to the driver) a YAML file for the PID. I've tried in the `hoverboard_controllers.yaml` like so:
```
PID:
  ros__parameters:
    f: 10.2
    p: 1.0
    i: 0.1
    d: 1.0
    i_clamp_min: -10.0
    i_clamp_max: 10.0
    antiwindup: false
```
and also replacing the "PID:" with "hoverboard_driver_node:" but I am still unsuccessful.

The error I am getting when selecting hoverboard_driver_node in rqt parameters reconfigure:
`[rqt_reconfigure]: Failed to retrieve parameters from node: asynchronous service call failed: the target node may not be spinning`

and also this:
```
$ ros2 param list /hoverboard_driver_node 
Exception while calling service of node '/hoverboard_driver_node': None
```

Also I wanted to ask how can I create/pass a config or yaml file for the PID...

Thank you

[image](https://github.com/user-attachments/assets/4ebf9541-c986-44f4-82ce-4b1bfef31793)
